services:
  init:
    image: alpine
    entrypoint: install -d -o ${NAS_UID:?} -g ${NAS_GID:?} -m 770
    volumes:
      - ${PATH_TO_ROOT:?}/monitoring:/tmp/monitoring
    command:
      - /tmp/monitoring/grafana/data
      - /tmp/monitoring/influxdb

  # https://hub.docker.com/r/grafana/grafana/tags
  grafana:
    image: grafana/grafana:11.6.0
    container_name: monitoring_grafana
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    networks:
      - default
      - proxy
    environment:
      TZ: ${TZ:?}
      INFLUXDB_DB: ${INFLUXDB_DB:?}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME:?}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD:?}
    volumes:
      - ${PATH_TO_ROOT:?}/monitoring/grafana/data:/var/lib/grafana
      - ${PATH_TO_ROOT:?}/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      init:
        condition: service_completed_successfully
      influxdb:
        condition: service_healthy

  # https://hub.docker.com/_/telegraf/tags
  telegraf:
    image: telegraf:1.34.1
    container_name: monitoring_telegraf
    restart: unless-stopped
    user: telegraf:${DOCKER_GID:?}
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB:?}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME:?}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD:?}
    volumes:
      - ${PATH_TO_ROOT:?}/monitoring/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    depends_on:
      influxdb:
        condition: service_healthy

  # https://hub.docker.com/_/influxdb/tags
  influxdb:
    image: influxdb:1.11.8
    container_name: monitoring_influxdb
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB:?}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_USERNAME:?}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_PASSWORD:?}
    volumes:
      - ${PATH_TO_ROOT:?}/monitoring/influxdb:/var/lib/influxdb
    depends_on:
      init:
        condition: service_completed_successfully
    healthcheck:
      test: "curl -f http://localhost:8086/health"
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  proxy:
    external: true
