services:
  grafana:
    image: grafana/grafana:11.5.2
    container_name: monitoring_grafana
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    ports:
      - 3000:3000
    environment:
      TZ: ${TZ:?}
      INFLUXDB_ORG: ${INFLUXDB_ORG:?}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET:?}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN:?}
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      influxdb:
        condition: service_healthy

  telegraf:
    image: telegraf:1.33
    container_name: monitoring_telegraf
    restart: unless-stopped
    user: telegraf:${DOCKER_GID:?}
    environment:
      INFLUXDB_ORG: ${INFLUXDB_ORG:?}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET:?}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN:?}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    depends_on:
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:2.7.11
    container_name: monitoring_influxdb
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:?}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:?}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME:?}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:?}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN:?}
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
