[[inputs.cpu]]
percpu = true
totalcpu = true
collect_cpu_time = false
report_active = false
core_tags = false

[[inputs.mem]]

[[inputs.disk]]
ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.net]]

[[inputs.docker]]
endpoint = "unix:///var/run/docker.sock"
gather_services = false
source_tag = false
container_name_include = []
container_name_exclude = []
timeout = "5s"
perdevice_include = ["cpu"]
total = false
docker_label_include = []
docker_label_exclude = []
tag_env = ["JAVA_HOME", "HEAP_SIZE"]

[[outputs.influxdb]]
urls = ["http://influxdb_v1:8086"]
timeout = "5s"
database = "${INFLUXDB_DB}"
username = "${INFLUXDB_USERNAME}"
password = "${INFLUXDB_PASSWORD}"

[[outputs.influxdb_v2]]
urls = ["http://influxdb_v2:8086"]
timeout = "5s"
organization = "${INFLUXDB_ORG}"
bucket = "${INFLUXDB_BUCKET}"
token = "${INFLUXDB_ADMIN_TOKEN}"
